/*jshint node:true*/
'use strict';

exports.suites = {
    start : [ // Test that the application is online
        './specs/e2e/universal_id/common/tests/launchApplicationTest.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/welcomePageTest.js',
    ],

    login : './specs/e2e/universal_id/common/tests/launchApplicationTest.js',

    read : './specs/e2e/universal_id/userscenario/registeruser/tests/readFile.js',

    regflow : [ // Test smaller set of positive scenarios when user uses phone as 2FA
        './specs/e2e/universal_id/common/tests/launchApplicationTest.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/chooseLanguageTest2.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/registrationStep1Test.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/personaDetailsPrimerPageTest.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/personalDetailsTest.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/personalCurrentAddressTest.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/personalInformationTest.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/confirmDetailsTest.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/secondFactorPhoneRegistrationTest.js',
    ],

    regflowNegativePhone : [ // Test negative scenarios when user uses phone as second factor authentication (2FA)
        './specs/e2e/universal_id/common/tests/launchApplicationTest.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/welcomePageTest.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/registrationStep1TestNegative.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/personaDetailsPrimerPageTest.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/personalDetailsTestNegative.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/personalCurrentAddressTestNegative.js',
        //'./specs/e2e/universal_id/userscenario/registeruser/tests/personalInformationTestNegative.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/confirmDetailsTestNegative.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/secondFactorPhoneRegistrationTestNegative.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/confirmPasscodeTestNegativePhone.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/myAccountSuccessTest.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/myAccountTestNegative.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/myAccountMenuTestNegative.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/myAccountPersonalDetailsTestNegative.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/myAccountTwoFactorDetailsPhoneTestNegative.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/myAccountAddPhoneTestNegative.js',
        //'./specs/e2e/universal_id/userscenario/registeruser/tests/myAccountSettingsTest.js',
    ],


    regflowNegativeEmail : [ // Test negative scenarios when user uses email as 2FA
        './specs/e2e/universal_id/common/tests/launchApplicationTest.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/welcomePageTest.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/registrationStep1TestNegative.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/personaDetailsPrimerPageTest.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/personalDetailsTestNegative.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/personalCurrentAddressTestNegative.js',
        // SSN and DOB pages were removed from scope of tests for now.
        //'./specs/e2e/universal_id/userscenario/registeruser/tests/personalInformationTestNegative.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/confirmDetailsTestNegative.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/secondFactorEmailRegistrationTestNegative.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/confirmPasscodeTestNegative.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/myAccountSuccessTest.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/myAccountTestNegative.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/myAccountMenuTestNegative.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/myAccountPersonalDetailsTestNegative.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/myAccountTwoFactorDetailsEmailTestNegative.js' ,
        './specs/e2e/universal_id/userscenario/registeruser/tests/myAccountAddEmailTestNegative.js',

    ],

    regflow1 : [ // Test positive scenarios when user uses phone as 2FA
        './specs/e2e/universal_id/common/tests/launchApplicationTest.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/welcomePageTest.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/registrationStep1Test.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/personalDetailsPrimerPageHelpMenuTest.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/personaDetailsPrimerPageTest.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/personalDetailsHelpMenuTest.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/personalDetailsTest.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/personalCurrentAddressHelpMenuTest.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/personalCurrentAddressTest.js',
        // SSN and DOB pages were removed from scope of tests for now.
        //'./specs/e2e/universal_id/userscenario/registeruser/tests/personalInformationHelpMenuTest.js',
        //'./specs/e2e/universal_id/userscenario/registeruser/tests/personalInformationTest.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/confirmDetailsTest.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/secondFactorPrimerHelpMenuTest.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/secondFactorPrimerPageTest.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/secondFactorSelectionPageHelpMenuTest.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/secondFactorSelectionPageTest.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/secondFactorPhoneRegistrationTest.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/myAccountSuccessTest.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/myAccountTest.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/myAccountMenuTest.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/myAccountPersonalDetailsHelpMenuTest.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/myAccountPersonalDetailsTest.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/myAccountTwoFactorDetailsPhoneTest.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/myAccountAddPhoneTest.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/myAccountRemovePhoneTest.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/myAccountSettingsTest.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/myAccountChangePasswordTest.js',
    ],


    regflow2 : [ // Test positive scenarios when user uses email as 2FA
        './specs/e2e/universal_id/common/tests/launchApplicationTest.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/welcomePageTest.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/registrationStep1Test.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/personalDetailsPrimerPageHelpMenuTest.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/personaDetailsPrimerPageTest.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/personalDetailsHelpMenuTest.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/personalDetailsTest.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/personalCurrentAddressHelpMenuTest.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/personalCurrentAddressTest.js',
        // SSN and DOB pages were removed from scope of tests for now.
        //'./specs/e2e/universal_id/userscenario/registeruser/tests/personalInformationHelpMenuTest.js',
        //'./specs/e2e/universal_id/userscenario/registeruser/tests/personalInformationTest.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/confirmDetailsTest.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/secondFactorPrimerHelpMenuTest.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/secondFactorPrimerPageTest.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/secondFactorSelectionPageHelpMenuTest.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/secondFactorSelectionPageTest.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/secondFactorEmailRegistrationTest.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/myAccountSuccessTest.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/myAccountTest.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/myAccountMenuTest.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/myAccountPersonalDetailsHelpMenuTest.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/myAccountPersonalDetailsTest.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/myAccountTwoFactorDetailsEmailTest.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/myAccountAddEmailTest.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/myAccountRemoveEmailTest.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/myAccountSettingsTest.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/myAccountChangePasswordTest.js',
    ],

    regflow3 : [ // Test positive scenarios when user uses security token as 2FA
        './specs/e2e/universal_id/common/tests/launchApplicationTest.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/welcomePageTest.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/registrationStep1Test.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/personaDetailsPrimerPageTest.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/personalDetailsTest.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/personalCurrentAddressTest.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/personalInformationTest.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/confirmDetailsTest.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/secondFactorTokenRegistrationTest.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/myAccountSuccessTest.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/myAccountTest.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/myAccountMenuTest.js',
        './specs/e2e/universal_id/userscenario/registeruser/tests/myAccountPersonalDetailsTest.js',
    ],
};
